---
- name: Create Projects and Policies
  hosts: bootstrap
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
      tags:
      - bootstrap
      - openshift-applier

- name: Create CI/CD pipeliene config for app
  hosts: ci-cd-app
  tasks:
    - include_vars: "{{ inventory_dir }}/../../encrypted-secrets.yml"
      when: "encrypted_gitea_key is not defined"

    - include_role:
        name: openshift-applier/roles/openshift-applier
      tags:
        - openshift-applier

- name: Create all the configuration needed by CI/CD jenkinsfile for app
  hosts: app
  tasks:
    - include_vars: "{{ inventory_dir }}/../../encrypted-secrets.yml"
      when: "encrypted_gitea_key is not defined"

    - include_role:
        name: openshift-applier/roles/openshift-applier
      tags:
        - openshift-applier
