---
ansible_connection: local

jenkins:
  ROLE: admin
  PIPELINES_NAMESPACE: "{{ projects.ci_cd_namespace }}"
  DEPLOYER_USER: jenkins

image_puller:
  ROLE: "system:image-puller"
  PIPELINES_NAMESPACE: "{{ projects.ci_cd_namespace }}"
  DEPLOYER_USER: default


image_pull_role_binding_ci_cdns:
  ROLE: "system:image-puller"
  GROUP: "system:serviceaccounts:coolstore-cicd"


image_pull_role_binding_devns:
  ROLE: "system:image-puller"
  GROUP: "system:serviceaccounts:coolstore-dev"


image_pull_role_binding_prodns:
  ROLE: "system:image-puller"
  GROUP: "system:serviceaccounts:coolstore-prod"


image_pull_role_binding_testns:
  ROLE: "system:image-puller"
  GROUP: "system:serviceaccounts:coolstore-test"



openshift_cluster_content:
- object: project
  content:

  - name: create coolstore-cicd
    template:  "{{ playbook_dir }}/templates/project/project-request-template.yaml" 
    params_from_vars: "{{ ci_cd }}"
    action: apply
    ignore_unknown_parameters: false
    tags:
    - projectrequests
    - projectrequests-ci_cd


  - name: create coolstore-dev
    template:  "{{ playbook_dir }}/templates/project/project-request-template.yaml" 
    params_from_vars: "{{ dev }}"
    action: apply
    ignore_unknown_parameters: false
    tags:
    - projectrequests
    - projectrequests-dev


  - name: create coolstore-prod
    template:  "{{ playbook_dir }}/templates/project/project-request-template.yaml" 
    params_from_vars: "{{ prod }}"
    action: apply
    ignore_unknown_parameters: false
    tags:
    - projectrequests
    - projectrequests-prod


  - name: create coolstore-test
    template:  "{{ playbook_dir }}/templates/project/project-request-template.yaml" 
    params_from_vars: "{{ test }}"
    action: apply
    ignore_unknown_parameters: false
    tags:
    - projectrequests
    - projectrequests-test



- object: group-role-binding
  content:

  - name: "edit-acl-in-coolstore-cicd"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/group-rolebinding-template.yml" 
    params_from_vars:  "{{ edit_role_binding_group }}" 
    namespace: "coolstore-cicd"
    tags:
    - "coolstore-cicd"
    - rolebinding-group
    - "rolebinding-group-coolstore-cicd"
  - name: "admin-acl-incoolstore-cicd"
    template:  "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/group-rolebinding-template.yml" 
    params_from_vars:  "{{ admin_role_binding_group }}" 
    namespace: "coolstore-cicd"
    tags:
    - "coolstore-cicd"
    - rolebinding-group
    - "rolebinding-group-coolstore-cicd"


  - name: "edit-acl-in-coolstore-dev"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/group-rolebinding-template.yml" 
    params_from_vars:  "{{ edit_role_binding_group }}" 
    namespace: "coolstore-dev"
    tags:
    - "coolstore-dev"
    - rolebinding-group
    - "rolebinding-group-coolstore-dev"
  - name: "admin-acl-incoolstore-dev"
    template:  "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/group-rolebinding-template.yml" 
    params_from_vars:  "{{ admin_role_binding_group }}" 
    namespace: "coolstore-dev"
    tags:
    - "coolstore-dev"
    - rolebinding-group
    - "rolebinding-group-coolstore-dev"


  - name: "edit-acl-in-coolstore-prod"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/group-rolebinding-template.yml" 
    params_from_vars:  "{{ edit_role_binding_group }}" 
    namespace: "coolstore-prod"
    tags:
    - "coolstore-prod"
    - rolebinding-group
    - "rolebinding-group-coolstore-prod"
  - name: "admin-acl-incoolstore-prod"
    template:  "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/group-rolebinding-template.yml" 
    params_from_vars:  "{{ admin_role_binding_group }}" 
    namespace: "coolstore-prod"
    tags:
    - "coolstore-prod"
    - rolebinding-group
    - "rolebinding-group-coolstore-prod"


  - name: "edit-acl-in-coolstore-test"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/group-rolebinding-template.yml" 
    params_from_vars:  "{{ edit_role_binding_group }}" 
    namespace: "coolstore-test"
    tags:
    - "coolstore-test"
    - rolebinding-group
    - "rolebinding-group-coolstore-test"
  - name: "admin-acl-incoolstore-test"
    template:  "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/group-rolebinding-template.yml" 
    params_from_vars:  "{{ admin_role_binding_group }}" 
    namespace: "coolstore-test"
    tags:
    - "coolstore-test"
    - rolebinding-group
    - "rolebinding-group-coolstore-test"



# Bindings to allow Jenkins operate outside of the project its project


- object: service-user-role-bind
  content:
  - name: "jenkins-coolstore-dev-role-binding"
    template:  "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/generic-service-user-bind.yml" 
    params_from_vars:  "{{ jenkins }}" 
    namespace: "coolstore-dev"
    tags:
    - "coolstore-dev"
    - rolebinding-jenkins
    - "rolebinding-jenkins-coolstore-dev"


- object: service-user-role-bind
  content:
  - name: "jenkins-coolstore-prod-role-binding"
    template:  "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/generic-service-user-bind.yml" 
    params_from_vars:  "{{ jenkins }}" 
    namespace: "coolstore-prod"
    tags:
    - "coolstore-prod"
    - rolebinding-jenkins
    - "rolebinding-jenkins-coolstore-prod"


- object: service-user-role-bind
  content:
  - name: "jenkins-coolstore-test-role-binding"
    template:  "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/generic-service-user-bind.yml" 
    params_from_vars:  "{{ jenkins }}" 
    namespace: "coolstore-test"
    tags:
    - "coolstore-test"
    - rolebinding-jenkins
    - "rolebinding-jenkins-coolstore-test"




# Add image puller role to be able to get images stored in other namespace
- object: image-puller-role-binding
  content:
  - name: "image-puller-{{ projects.dev_namespace }}-role-binding"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/generic-service-user-bind.yml"
    params_from_vars: "{{ image_puller }}"
    namespace: "{{ projects.dev_namespace }}"
    tags:
    - "{{ projects.dev_namespace }}"
    - rolebinding-image-puller
    - "rolebinding-image-puller-{{ projects.dev_namespace }}"



#to be able to pull images from dev project by service accounts from other projects in pipeline
- object: image-puller-role-binding
  content:



  - name: "serviceaccount-coolstore-prod-role-binding"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/group-rolebinding-template.yml"
    params_from_vars: "{{image_pull_role_binding_prodns}}"
    namespace: "coolstore-dev"
    tags:
    - "coolstore-prod"
    - rolebinding-image-puller
    - "rolebinding-image-puller-coolstore-prod"


  - name: "serviceaccount-coolstore-test-role-binding"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/role-bindings/group-rolebinding-template.yml"
    params_from_vars: "{{image_pull_role_binding_testns}}"
    namespace: "coolstore-dev"
    tags:
    - "coolstore-test"
    - rolebinding-image-puller
    - "rolebinding-image-puller-coolstore-test"

