apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${APP_NAME}-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: coolstore
      application: coolstore
      component: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: coolstore
      app: coolstore
      component: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          application: coolstore
          component: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
        name: ${APP_NAME}
      spec:
        containers:
        - env:
          - name: CATALOG_ENDPOINT
            value: http://catalog:8080
          - name: APPLICATION_MODE
            value: prod
          - name: DATAGRID_HOST
            value: datagrid-hotrod
          - name: DATAGRID_PORT
            value: "11333"
          image: docker-registry.default.svc:5000/${BUILD_NAMESPACE}/${APP_NAME}:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: ${APP_NAME}
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: cart:latest-green
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      application: coolstore
      component: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
# Cart Route
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/balance: roundrobin
    name: cart
    labels:
      application: coolstore
      component: cart
  spec:
    alternateBackends:
      - kind: Service
        name: ${APP_NAME}
        weight: 100
    to:
      kind: Service
      name: cart-blue
      weight: 0
    wildcardPolicy: None
parameters:
- description: BUILD_NAMESPACE
  displayName: BUILD_NAMESPACE
  name: BUILD_NAMESPACE
  required: true
- description: APP_NAME
  displayName: APP_NAME
  name: APP_NAME
  required: true