---
ansible_connection: local

openshift_templates_raw: "https://raw.githubusercontent.com/rht-labs/openshift-templates"
openshift_templates_raw_version_tag: "v1.4.3"

#nexus details
nexus:
  server: nexus-infra-tools.apps.cluster-d327.d327.sandbox321.opentlc.com
  user: admin
  password: admin123

admin_role_binding_group:
  GROUP: "Admins"
  ROLE: "admin"

edit_role_binding_group:
  GROUP: "{{ acls.devgroup }}"
  ROLE: "{{ role | default('edit') }}"

ci_cd:
  NAMESPACE: "{{ projects.ci_cd_namespace }}"
  NAMESPACE_DISPLAY_NAME: "{{ projects.ci_cd_namespace }}" 
  DEFAULT_MEM_LIMIT: "4Gi" 
  DEFAULT_MEM_REQUEST: "2Gi"

jenkinslaves:
- agent-nodejs
- agent-maven