---
baseimagepipeline:
  BUILD_NAMESPACE: "{{ dev_namespace }}"
  GIT_URL: "{{ scm_url }}"
  GIT_BRANCH: "{{ scm_branch }}"
  GIT_SECRET: "{{ scm_secret_name }}"
  APP_NAME: "{{ app_name }}"
  DOCKERFILE_CONTEXT_DIR: "{{ docker_file_contextdir }}"
  
openshift_cluster_content:
- object: baseimage-components
  content:
    - name: ssh-private-key
      template: "{{ inventory_dir }}/../templates/secret/secret-ssh-private-key-template.yaml"
      params_from_vars:
        SECRET_NAME: gitea
        SSH_PRIVATE_KEY: "{{ encrypted_gitea_key }}"
      namespace: "{{ dev_namespace }}"
      tags:
      - ssh-private-key

    - name: baseimage
      template: "{{ inventory_dir }}/../templates/app/generic.yaml"
      params_from_vars: "{{ baseimagepipeline }}"
      namespace: "{{ dev_namespace }}"
      ignore_unknown_parameters: false
      tags:
      - app
